version: '3.1'

services:
  development-db:
    image: postgres:17.0
    container_name: repuestos-facil-development-db
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=repuestos-facil-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: repuestos-facil-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - development-db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge