version: '3.1'

services:
  development-db:
    image: postgres:17.0
    container_name: repuestos-facil-development-db
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=repuestos-facil-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: repuestos-facil-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - development-db
    networks:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Para optimizar rendimiento
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Limitar memoria para JVM
      - xpack.security.enabled=false # Desactivar seguridad en entornos de prueba
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - postgres

networks:
  postgres:
    driver: bridge